home: "{{ ansible_env.HOME }}"

xdg_bin: "{{ home }}/.local/bin"
xdg_config_home: "{{ home }}/.config"
xdg_data_home: "{{ home }}/.local/share"
xdg_cache_home: "{{ home }}/.cache"

packages:
  - build-essential
  - apt-transport-https
  - ca-certificates
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - llvm
  - tk-dev
  - libncurses5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - lsb-release

  - zsh

  - tmux
  - neovim

  - curl
  - wget
  - make
  - jq
  - htop
  - bpftrace
  - gnupg

  # Less source highlighting
  - source-highlight
  - libsource-highlight-common

macos_homebrew_applications: []

vscode_extensions:
  - ms-dotnettools.csharp
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-azuretools.vscode-docker
  - eamodio.gitlens
  - jtlowe.vscode-icon-theme
  - dbaeumer.vscode-eslint
  - esbenp.prettier-vscode
  - streetsidesoftware.code-spell-checker
  - github.vscode-pull-request-github
  - editorconfig.editorconfig
  - monokai.theme-monokai-pro-vscode
  - pflannery.vscode-versionlens
  - golang.go
  - matklad.rust-analyzer
  - hashicorp.terraform
