- name: Set up local workstation
  hosts: local
  gather_facts: yes
  roles:
    - role: common
    - role: shell
    - role: python
      tags:
        - programming
        - python
    - role: rust
      tags:
        - programming
        - rust
    - role: tmux
    - role: nvim
    - role: kubectl
    - role: docker
    - role: macos-defaults
      when: ansible_os_family == "Darwin"
