- name: Set up local workstation
  hosts: all
  gather_facts: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include extra config file.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - import_tasks: tasks/sync_dotfiles.yml
      tags:
        - dotfiles

    - import_tasks: tasks/install_packages.yml
      tags:
        - packages

    - import_role:
        name: macos
      tags:
        - apps
        - macos
      when: ansible_os_family == "Darwin"

    - import_tasks: tasks/configure_zsh.yml
      tags:
        - zsh

    - import_tasks: tasks/install_tmux_plugins.yml
      tags:
        - plugins
        - tmux

    - import_role:
        name: kubernetes
      tags:
        - kubernetes

    - import_role:
        name: docker
      tags:
        - docker

    - import_tasks: tasks/install_vscode.yml
      tags:
        - editors
