- name: Set z_dot_dir
  set_fact:
    z_dot_dir: "{{ xdg_config_home }}/shell"

- name: Install Oh My ZSH
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ z_dot_dir }}/oh-my-zsh"
    clone: yes
    update: yes

- name: Install ZSH Auto Suggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ z_dot_dir }}/custom/plugins/zsh-autosuggestions"
    clone: yes
    update: yes

- name: Install ZSH Syntax Highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ z_dot_dir }}/custom/plugins/zsh-syntax-highlighting"
    clone: yes
    update: yes

- name: ZSH as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
