- name: Synchronize dotfiles
  ansible.posix.synchronize:
    src: dotfiles/
    dest: "{{ home }}"

- name: Create .profile symlink
  file:
    src: "{{ xdg_config_home }}/shell/profile"
    dest: "{{ home }}/.profile"
    state: link

- name: Create .zprofile symlink
  file:
    src: "{{ xdg_config_home }}/shell/profile"
    dest: "{{ home }}/.zprofile"
    state: link
