#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias code="code --user-data-dir $XDG_DATA_HOME/vscode --extensions-dir $XDG_DATA_HOME/vscode/extensions"

alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -ql" \
    mkd="mkdir -pv" \
    ip="ip --color=auto"

alias tfs="tfswitch -b /home/nickvd/.local/bin/terraform"

# Utilities
alias myip="dig txt ch +short whoami.cloudflare @1.1.1.1"
alias myip6="dig txt ch +short whoami.cloudflare @2606:4700:4700::1111"
alias tun0="ip -o -4 addr list tun0 | awk -F ' *|/' '{print \$4}' | clip"
alias path="echo \$PATH | sed 's/:/\n/g'"
alias tms="tmux-sessionizer"
alias ls="eza --git"
alias tree="eza --tree --long --ignore-glob .git"

# MacOS alias overrides
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias clip="pbcopy"
    alias cat=bat
else
    alias clip="xclip -selection clipboard"
    alias cat=batcat
    alias open=xdg-open
fi
