#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Configure LANGs
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Default programs:
export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# XDG Configuration
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_BIN_HOME="$HOME/.local/bin"
export XDG_CACHE_HOME="$HOME/.cache"

export LESSHISTFILE="-"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# Golang:
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"
export PATH="$PATH:/usr/local/go/bin:$GOPATH/bin"

# Rust:
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export PATH="$PATH:$CARGO_HOME/bin"

# Dotnet:
# TODO: Move this out of $HOME at some point
# The following allows relocating some of it, but dotnet will still put files in .dotnet
# https://github.com/dotnet/sdk/blob/870254bacc3f169789b679e6e39420875b5d9b56/src/Cli/Microsoft.DotNet.Configurer/CliFolderPathCalculator.cs#L14
# export DOTNET_CLI_HOME="$DOTNET_INSTALL_DIR"
export DOTNET_INSTALL_DIR="$HOME/.dotnet"
export DOTNET_ROOT="$DOTNET_INSTALL_DIR"
export PATH="$PATH:$DOTNET_INSTALL_DIR:$DOTNET_INSTALL_DIR/tools"

export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGet/packages"
export NUGET_PLUGINS_CACHE_PATH="$XDG_CACHE_HOME/NuGet/plugins-cache"

# AWS Cli
# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
export AWS_CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/aws/config"
export AWS_SHARED_CREDENTIALS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/aws/credentials"

# Azure CLI
# https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file
export AZURE_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/azure"

# GnuPG
export GNUPGHOME="${XDG_DATA_HOME:-$HOME/.local/share}/gnupg"

# K9S
export K9SCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/k9s"

# NPM
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

# NVM
export NVM_DIR="$XDG_DATA_HOME/nvm"

# Deno
export DENO_INSTALL_ROOT="$XDG_BIN_HOME/.."

# Pyenv
export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"

# Z
export _Z_DATA="$XDG_CACHE_HOME/z"

# Indicate profile loaded
export PROFILE_LOADED=1
