Host 192.168.10.*
  User admin
  IdentityAgent SSH_AUTH_SOCK
  IdentityFile ~/.ssh/id_rsa
  IdentitiesOnly yes
  PubkeyAuthentication yes
  PreferredAuthentications publickey
  PasswordAuthentication no
  KbdInteractiveAuthentication no
