#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

alias clip="xclip -selection clipboard"
alias code="code --user-data-dir $XDG_DATA_HOME/vscode --extensions-dir $XDG_DATA_HOME/vscode/extensions"

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv"

alias open=xdg-open

alias tfs="tfswitch -b /home/nickvd/.local/bin/terraform"

# Utilities
alias myip="dig txt ch +short whoami.cloudflare @1.1.1.1"
alias myip6="dig txt ch +short whoami.cloudflare @2606:4700:4700::1111"

body() {
    IFS= read -r header
    printf '%s\n' "$header"
    "$@"
}
