packages:
  - linux-headers

  # Fonts
  - ttf-jetbrains-mono-nerd

  # Utilities
  - brightnessctl

  - hyprland
  - hypridle
  - hyprlock
  - hyprpaper
  - waybar
  - wofi

  - atuin
  - jq
  - go-yq
  - lazygit
  - tmux
  - ripgrep
  - fzf
  - fd
  - bat
  - eza
  - tokei
  - rsync
  - less
  - openssh
  - tealdeer
  - btop
  - direnv
