---
- name: Get kubectl version
  shell: |
    if ! [ -x "$(command -v kubectl)" ]; then
      printf '{ "clientVersion": { "gitVersion": ""} }'
    else
      printf "$(kubectl version --short=true --client=true -o json)"
    fi
  register: current_version

- name: Set kubectl version as json
  set_fact:
    current_version_json: "{{ current_version.stdout | from_json }}"

- name: Current kubectl version
  debug: msg="{{ current_version_json['clientVersion']['gitVersion'] }}"

- name: Download kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/{{ ansible_system | lower }}/amd64/kubectl"
    dest: /tmp/kubectl
    checksum: "{{ kubectl_checksum }}"
  when: "current_version_json['clientVersion']['gitVersion'] != kubectl_version"

- name: Copy kubectl binary to bin folder
  copy:
    src: "/tmp/kubectl"
    dest: "{{ kubectl_bin_directory}}/kubectl"
    mode: "{{ kubectl_binary_mode }}"
    owner: "{{ kubectl_owner }}"
    group: "{{ kubectl_group }}"
  become: true
  when: "current_version_json['clientVersion']['gitVersion'] != kubectl_version"
