---
- name: Apt Update registry
  apt:
    update_cache: yes
  become: true

- name: Apt Install Dev Utilities
  apt:
    pkg:
      - build-essential
      - apt-transport-https
      - ca-certificates
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - tk-dev
      - libncurses5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
      - lsb-release
  become: true

- name: Apt Install CLI Utilities
  apt:
    pkg:
      - curl
      - wget
      - make
      - jq
      - htop
      - bpftrace
      - gnupg
  become: true

- name: Apt install less is more
  apt:
    pkg:
      - source-highlight
      - libsource-highlight-common
  become: true
