#!/usr/bin/env sh

set -eou pipefail

function have {
  command -v "$1" &>/dev/null
}

# install ansible
have ansible || sudo pacman -S ansible

# Run Ansible
pushd ansible
ansible-playbook -i ./hosts ./linux.yml --ask-become-pass
popd
