---
- name: Determine if Docker was already installed
  shell: which docker
  register: docker_cmd_available
  ignore_errors: yes
  changed_when: False

- name: Set fact docker_installed
  set_fact: docker_installed={{ docker_cmd_available.rc == 0 }}
  when: docker_cmd_available is defined and docker_cmd_available.rc is defined
  changed_when: False

- name: Install the dependencies of Docker CE
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
  become: true
  when: not docker_installed

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: not docker_installed and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS')

- name: Add Docker stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  become: true
  when: not docker_installed and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS')

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true
  when: not docker_installed and ansible_distribution == 'Debian'

- name: Add Docker stable repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  become: true
  when: not docker_installed and ansible_distribution == 'Debian'

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: true
    state: present
  become: true
  when: not docker_installed

- name: Install Docker Cli
  apt:
    name: docker-ce-cli
    update_cache: true
    state: present
  become: true
  when: not docker_installed

- name: Install Containerd
  apt:
    name: containerd.io
    update_cache: true
    state: present
  become: true

- name: Install Docker Compose
  apt:
    name: docker-compose
    update_cache: true
    state: present
  become: true

- name: Create the Docker group
  group:
    name: docker
    state: present
  become: true

- name: Add user to the Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true

- name: Activate group changes
  shell: newgrp docker
