[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14

[colors]
[colors.primary]
background = '#1f1f28'
foreground = '#dcd7ba'

[colors.normal]
black   = '#090618'
red     = '#c34043'
green   = '#76946a'
yellow  = '#c0a36e'
blue    = '#7e9cd8'
magenta = '#957fb8'
cyan    = '#6a9589'
white   = '#c8c093'

[colors.bright]
black   = '#727169'
red     = '#e82424'
green   = '#98bb6c'
yellow  = '#e6c384'
blue    = '#7fb4ca'
magenta = '#938aa9'
cyan    = '#7aa89f'
white   = '#dcd7ba'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'

[keyboard]
bindings = [
    { key = "v",     mods = "Alt",     action = "Paste" },
    { key = "c",     mods = "Alt",     action = "Copy" },
    { key = "=",     mods = "Alt",     action = "IncreaseFontSize" },
    { key = "-",     mods = "Alt",     action = "DecreaseFontSize" },
    { key = "0",     mods = "Alt",     action = "ResetFontSize" },

    { key = ";",     mods = "Alt",     chars = "\u001b;"},
    
    { key = "Right", mods = "Alt",     chars = "\u001bf" },
    { key = "Left",  mods = "Alt",     chars = "\u001bb" },

    { key = "Left",  mods = "Command", chars = "\u001bOH", mode = "AppCursor" },
    { key = "Right", mods = "Command", chars = "\u001bOF", mode = "AppCursor" },
]

[window]
decorations = "Buttonless"
padding = { x=3, y=5 }
opacity = 0.97
